### ISSUE TITLE
Crash 로그

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#11]
```
2021-08-12 17:07:24.441 16323-16323/com.tmap.auto.KiaTaxi E/CAR.L: cannot get car_service, waited for car service (ms):5000
    java.lang.RuntimeException
        at android.car.Car.createCar(Car.java:871)
        at android.car.Car.createCar(Car.java:829)
        at com.skt.tmap.core.ui.vm.CarViewModel.connectCar(CarViewModel.java:133)
        at com.skt.tmap.auto.activity.TmapAutoNaviActivity.initViewModels(TmapAutoNaviActivity.java:453)
        at com.skt.tmap.auto.activity.TmapAutoNaviActivity.onCreate(TmapAutoNaviActivity.java:668)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by aqkhsg** [comment]
어떤 동작하다 죽는건지 알 수 있을까요? 실행하자마자 죽은건가요?

**Comment by jhanulis7** [comment]
아 아닙니다. 이것저것 하다가 죽은건데요.. 로그만 보고 아실까 싶어서요..

**Comment by aqkhsg** [comment]
확인 해보니 해당 로그는 car 라이브러리가 지원되지 않는 스마트폰이나 태블릿에서 초기 구동시점에 항상 출력되는 에러로 앱 동작에는 영향이 없습니다.

**Comment by jhanulis7** [comment]
이 이슈는 vr 과 관련없으므로 클로스합니다.
