### ISSUE TITLE
약관 미동의 상태 > requestSimpleTbt 만 호출 > 크래쉬

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#51]
- 약관 미동의 상태 > requestSimpleTbt 만 호출 > 크래쉬
  - VR 에서도 약관처리해서 호출하도록 변경함.
  - Tmap 도 크래쉬 nullable 방어코드 필요
```
<html>
<body>


16575 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | java.lang.NullPointerException: Attempt to invoke virtual method android.content.ContentResolver android.content.Context.getContentResolver() on a null object reference
-- | -- | -- | -- | -- | -- | -- | -- | --
16576 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | at com.skt.tmap.util.SystemInfo.isGpsEnabled(SystemInfo.java:330)
16577 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | at com.skt.tmap.location.TmapNaviLocationManager.onLocationChanged(TmapNaviLocationManager.java:260)
16578 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | at com.skt.tmap.engine.navigation.location.TmapLocationManager$1.run(TmapLocationManager.java:95)
16579 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | at android.os.Handler.handleCallback(Handler.java:938)
16580 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | at android.os.Handler.dispatchMessage(Handler.java:99)
16581 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | at android.os.Looper.loop(Looper.java:246)
16582 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | at android.app.ActivityThread.main(ActivityThread.java:8512)
16583 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | at java.lang.reflect.Method.invoke(Native Method)
16584 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
16585 | 09-15 | 10:50:05.620 | W | 28050 | 28050 | System.err: |   | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)


</body>
</html>

```
```
<html>
<body>


21192 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | FATAL EXCEPTION: Thread-6
-- | -- | -- | -- | -- | -- | -- | -- | --
21193 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | Process: com.tmap.auto.KiaTaxi, PID: 28050
21194 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | java.lang.RuntimeException: Cant create handler inside thread Thread[Thread-6,5,main] that has not called Looper.prepare()
21195 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | at android.os.Handler.(Handler.java:227)
21196 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | at android.os.Handler.(Handler.java:129)
21197 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | at android.os.CountDownTimer$1.(CountDownTimer.java:114)
21198 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | at android.os.CountDownTimer.(CountDownTimer.java:114)
21199 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | at com.tmap.auto.edith.EdithCallbackManager$1.(EdithCallbackManager.java:294)
21200 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | at com.tmap.auto.edith.EdithCallbackManager.(EdithCallbackManager.java:294)
21201 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | at com.tmap.auto.edith.EdithCallbackManager.getInstance(EdithCallbackManager.java:82)
21202 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | at com.tmap.auto.TmapAutoReceiver.doEdithCommand(TmapAutoReceiver.java:67)
21203 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | at com.tmap.auto.TmapAutoReceiver.access$100(TmapAutoReceiver.java:39)
21204 | 09-15 | 10:51:17.618 | E | 28050 | 28545 | AndroidRuntime: |   | at com.tmap.auto.TmapAutoReceiver$AppForegroudCheckerThread.run(TmapAutoReceiver.java:121)


</body>
</html>

```

**Comment by aqkhsg** [comment]
9/23버전에 수정되었습니다.

**Comment by jhanulis7** [comment]
- 9/23 확인, 이슈 클로스
