### ISSUE TITLE
약관 팝업 > reqCurr > 홈버튼 > reqCurr > 약관 팝업 > 약관선택 > 여러번 테스트 후  > 크래쉬

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#52]
약관 팝업 > reqCurr > 홈버튼 > reqCurr > 약관 팝업 > 약관선택 > 여러번 테스트 후  > 크래쉬
[LogFilter_20210915_105048.txt.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7166235/LogFilter_20210915_105048.txt.zip)
녹화 영상 별도로 성민님 전달
```
<html>
<body>


71736 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | FATAL EXCEPTION: main
-- | -- | -- | -- | -- | -- | -- | -- | --
71737 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | Process: com.tmap.auto.KiaTaxi, PID: 28050
71738 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.REQUEST_NAVI flg=0x10 (has extras) } in com.tmap.auto.TmapAutoReceiver@7c2dd44
71739 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1676)
71740 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at android.app.-$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
71741 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at android.os.Handler.handleCallback(Handler.java:938)
71742 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at android.os.Handler.dispatchMessage(Handler.java:99)
71743 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at android.os.Looper.loop(Looper.java:246)
71744 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at android.app.ActivityThread.main(ActivityThread.java:8512)
71745 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at java.lang.reflect.Method.invoke(Native Method)
71746 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
71747 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
71748 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | Caused by: java.lang.RuntimeException: Could not dispatch event: class com.skt.tmap.util.BusEvent to handler [EventHandler public void com.skt.tmap.auto.activity.TmapAutoNaviActivity.receiveBusEvent(com.skt.tmap.util.BusEvent)]: Attempt to invoke virtual method void com.skt.tmap.mapview.streaming.MapViewStreaming.removeCalloutPopup(boolean) on a null object reference
71749 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
71750 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.squareup.otto.Bus.dispatch(Bus.java:387)
71751 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
71752 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.squareup.otto.Bus.post(Bus.java:337)
71753 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.skt.tmap.util.BusThread.post(BusThread.java:14)
71754 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.tmap.auto.edith.EdithDataReceiveManager.reqCurrLocation(EdithDataReceiveManager.java:54)
71755 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.tmap.auto.TmapAutoReceiver.doEdithCommand(TmapAutoReceiver.java:71)
71756 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.tmap.auto.TmapAutoReceiver.onReceive(TmapAutoReceiver.java:53)
71757 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1666)
71758 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | ... 8 more
71759 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | Caused by: java.lang.NullPointerException: Attempt to invoke virtual method void com.skt.tmap.mapview.streaming.MapViewStreaming.removeCalloutPopup(boolean) on a null object reference
71760 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.skt.tmap.auto.activity.TmapAutoNaviActivity.clickCurrentLocationButton(TmapAutoNaviActivity.java:2818)
71761 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.skt.tmap.auto.activity.TmapAutoNaviActivity.setCurrentLocationModeVRCmd(TmapAutoNaviActivity.java:2791)
71762 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.skt.tmap.auto.activity.TmapAutoNaviActivity.receiveBusEvent(TmapAutoNaviActivity.java:10665)
71763 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at java.lang.reflect.Method.invoke(Native Method)
71764 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
71765 | 09-15 | 11:14:42.697 | E | 28050 | 28050 | AndroidRuntime: |   | at com.squareup.otto.Bus.dispatch(Bus.java:385)


</body>
</html>�

```

**Comment by aqkhsg** [comment]
9/23버전에 수정되었습니다.

**Comment by jhanulis7** [comment]
- 9/23 확인, 이슈 클로스
