### ISSUE TITLE
[Navigation][기능] Tmap 검색창 히스토리에서 POI 선택시 Tmap 중지팝업 발생 현상

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#70]
[PBV01QA-142 (2).zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7509929/PBV01QA-142.2.zip)

내부 QA 이슈입니다.
수정이 완료 되었으면 공유 부탁드립니다.

```
11-02 10:08:35.481 E/AndroidRuntime( 3675): FATAL EXCEPTION: Thread-25
11-02 10:08:35.481 E/AndroidRuntime( 3675): Process: com.tmap.auto.KiaTaxi, PID: 3675
11-02 10:08:35.481 E/AndroidRuntime( 3675): java.lang.NullPointerException: Attempt to invoke virtual method 'void d.i.d.l0.x0.b.a(android.content.Context, d.b.b.o$b, d.b.b.o$a)' on a null object reference
11-02 10:08:35.481 E/AndroidRuntime( 3675): 	at d.i.d.o.b.f.v2$i.run(SourceFile:3)
11-02 10:08:35.481 E/AndroidRuntime( 3675): 	at java.lang.Thread.run(Thread.java:919)
11-02 11:15:46.209 E/AndroidRuntime( 3675): FATAL EXCEPTION: main
11-02 11:15:46.209 E/AndroidRuntime( 3675): Process: com.tmap.auto.KiaTaxi, PID: 3675
11-02 11:15:46.209 E/AndroidRuntime( 3675): java.lang.ClassCastException: java.lang.Object[] cannot be cast to com.skt.tmap.engine.navigation.network.ndds.NddsDataType$EvSocketType[]
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.g.a(SourceFile:272)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.c.accept(Unknown Source:4)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at java.util.ArrayList.forEach(ArrayList.java:1262)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.g.h(SourceFile:5)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.g.a(SourceFile:237)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.g.c(SourceFile:39)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.g.a(SourceFile:117)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.g.b(SourceFile:20)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.g.a(SourceFile:29)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.g.a(SourceFile:18)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.d$a.a(SourceFile:14)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.d.a(SourceFile:55)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.d.a(SourceFile:25)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.d.a(SourceFile:21)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.d.a(SourceFile:7)
11-02 11:15:46.209 E/AndroidRuntime( 3675): 	at d.i.d.g0.j.d.a(SourceFile:3)
```

[빌드 버전]

QA 0.4.8
[테스트 환경 정보]
Mobile - Device : AVN

[발생 빈도]
1/10

[이슈 현상]
Tmap 검색창 히스토리에서 POI 선택시 Tmap 중지팝업 발생 현상 (재부팅후 정상동작함)

[사전 조건]
1. 배터리 0% 로 설정된 상태
2. History 에 POI 저장되있는 상태

[재현 스텝]
1. Tmap 에서 검색창 활성화 > History에서 저장된 POI 선택

[기대 결과]
중지팝업 발생하면 안됨

[기타 참고사항]
재현시간 : 2021.11.02 오전 11시 28분 이후

**Comment by aqkhsg** [comment]
최신버전 (0.6.1) 에 수정되었습니다.

**Comment by jhanulis7** [comment]
- 정식 버젼 0.6.1 수정, 확인 할수가 앖어서 이슈 클로스 합니다.
