### ISSUE TITLE
길 안내 중 "근처 유치원 찾아줘" 발화한 뒤 리스트 목록에서 임의로 선택 시 T map 튕기는 현상

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#81]
https://cody-ims.autoever.com/browse/PBV01QA-232
[빌드 버전]

VR 0.5.3
Tmap 0.6.3
[테스트 환경 정보]
Mobile - Device : Tablet / AVN

[발생 빈도]
10/10

[이슈 현상]
임의 목적지 길 안내 중에 경유지 2개 추가된 상태에서 "근처 유치원 찾아줘" 발화한 뒤 리스트 목록에서 임의로 선택 시 T map 튕기는 현상

[사전 조건]
길 안내 중인 상태

[재현 스텝]
길 안내 중 (경유지 2개 추가된 상태) > "근처 유치원 찾아줘" 발화 > 리스트 목록에서 임의로 선택

[기대 결과]
중지 팝업 발생하면 안됨

```
11-25 13:45:21.481 12359 12359 E AndroidRuntime: FATAL EXCEPTION: main
11-25 13:45:21.481 12359 12359 E AndroidRuntime: Process: com.tmap.auto.KiaTaxi, PID: 12359
11-25 13:45:21.481 12359 12359 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void d.i.d.l.k.q6.f1()' on a null object reference
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at com.skt.tmap.auto.activity.TmapAutoNaviActivity.t0(SourceFile:4)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at com.skt.tmap.auto.activity.TmapAutoNaviActivity.o(SourceFile:29)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at com.skt.tmap.auto.activity.TmapAutoNaviActivity.e(SourceFile:3)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at com.skt.tmap.auto.activity.TmapAutoNaviActivity$u.a(SourceFile:7)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at d.i.d.l.f.m.run(Unknown Source:4)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7368)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
11-25 13:45:21.481 12359 12359 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1108)
```

**Comment by aqkhsg** [comment]
수정하였고 다음 배포 버전에 반영예정입니다.

**Comment by aqkhsg** [comment]
0.10.1 버전에 수정되었습니다.
