### ISSUE TITLE
 java.lang.ClassCastException: d.i.d.a0.c.d.e cannot be cast to d.i.d.a0.c.d.a 2

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#82]
개발 테스트 중 발생
VR 서울역 > 리트스 중  > 1번째 터치로 선택> 티맵 아무 반응없음

v0.9.1

```
2021-12-13 12:47:31.881 1991-2175/? D/MobileSignalIconsSelector: getDataIconGroup(): connected=false,enabled=true,level=0,inetCondition=1,dataIconGroup=DataIconGroup(UNKNOWN),activityIn=false,activityOut=false,lastModified=12-13 09:54:08.478,dataSim=true,networkName=제한구역서비스,networkNameData=제한구역서비스,dataConnected=false,roaming=false,isDefault=false,isEmergency=true,airplaneMode=false,carrierNetworkChangeMode=false,userSetup=true,defaultDataOff=false,cdmaEriIconIndex=-1,cdmaEriIconMode=-1,callState=0,voWifiConnected=false,shouldShowDisabledDataIcon=false,bluetoothTethered=false,isLTEFemtoCell=false,cardOperator=OTHERS,optionalRadioTech=0,isCAIndicator=false,isLimitedStateForCTCSlaveVoLTE=false,isSWRoaming=false,isMobileDataSettingEnabled=false,nwBoosterRilEnabled=false,nwBoosterSettingEnabled=false,emergencyModeActivated=false,ismmW5G=false,slotId=0,simState=ABSENT, iconSet = null
2021-12-13 12:47:40.781 16670-16670/? W/System.err: java.lang.ClassCastException: d.i.d.a0.c.d.e cannot be cast to d.i.d.a0.c.d.a
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at d.i.d.a0.c.d.e.equals(SourceFile:2)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at d.i.d.a0.c.e.e.a(SourceFile:12)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at d.i.d.a0.c.c.a(SourceFile:5)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at com.skt.tmap.mapview.streaming.MapViewStreaming.a(SourceFile:162)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at d.i.d.z.a.a(SourceFile:25)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at com.skt.tmap.auto.activity.TmapAutoNaviActivity.c(SourceFile:40)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at d.i.d.l.f.c.a(Unknown Source:2)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at d.i.d.r.h.l.d.a(SourceFile:16)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at com.skt.tmap.network.TmapNetworkRequester.a(SourceFile:58)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at d.i.d.r.h.l.d$a.b(SourceFile:1)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at d.i.d.r.h.l.j.b.b(SourceFile:10)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at d.i.d.r.h.l.j.e.b(SourceFile:1)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at com.skt.tmap.network.task.TmapURLConnectionTask.b(SourceFile:1)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at com.skt.tmap.network.task.TmapURLConnectionTask.onPostExecute(SourceFile:1)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:771)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at android.os.AsyncTask.access$900(AsyncTask.java:199)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at android.os.Looper.loop(Looper.java:247)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8618)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
2021-12-13 12:47:40.781 16670-16670/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-12-13 12:47:57.544 16670-29092/? W/System.err: java.io.FileNotFoundException: /proc/stat: open failed: EACCES (Permission denied)
2021-12-13 12:47:57.544 16670-29092/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:492)
2021-12-13 12:47:57.544 16670-29092/? W/System.err:     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
2021-12-13 12:47:57.544 16670-29092/? W/System.err:     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
2021-12-13 12:47:57.544 16670-29092/? W/System.err:     at d.i.d.l0.n0$b.a(SourceFile:2)
2021-12-13 12:47:57.544 16670-29092/? W/System.err:     at d.i.d.l0.n0$b.doInBackground(SourceFile:1)
2021-12-13 12:47:57.544 16670-29092/? W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
2021-12-13 12:47:57.544 16670-29092/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-12-13 12:47:57.544 16670-29092/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-12-13 12:47:57.544 16670-29092/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-12-13 12:47:57.544 16670-29092/? W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-12-13 12:47:57.545 16670-29092/? W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
2021-12-13 12:47:57.545 16670-29092/? W/System.err:     at libcore.io.Linux.open(Native Method)
2021-12-13 12:47:57.545 16670-29092/? W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
2021-12-13 12:47:57.545 16670-29092/? W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
2021-12-13 12:47:57.545 16670-29092/? W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
2021-12-13 12:47:57.545 16670-29092/? W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8479)
2021-12-13 12:47:57.545 16670-29092/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:478)
2021-12-13 12:47:57.545 16670-29092/? W/System.err: 	... 9 more
2021-12-13 12:48:05.914 3088-2906/? V/NativeCrypto: SSL shutdown failed: ssl=0xb4000074f4875f48: I/O error during system call, Broken pipe
```

**Comment by jhanulis7** [comment]
요 로그만 보고, f/u 어려울까요? 그럼 이슈 클로스 하겠습니다.

**Comment by aqkhsg** [comment]
네 재현이 안되고 해당 로그만으로는 정확한 위치를 알기가 어렵네요.
재현 안되니 우선 클로스 부탁드리겠습니다.
이후에 혹시 다시 발생하면 추가분석해보겠습니다.

**Comment by jhanulis7** [comment]
필드이슈로 커버한다고 보고 이슈 클로스함
