### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#89]
````
<html>
<body>


241658 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | FATAL EXCEPTION: main
-- | -- | -- | -- | -- | -- | -- | -- | --
241659 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | Process: com.tmap.auto.KiaTaxi, PID: 26889
241660 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | java.lang.NullPointerException: Attempt to invoke virtual method byte[] com.skt.tmap.engine.navigation.network.RouteSearchData.getfurName() on a null object reference
241661 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at d.l.a.b.j.a(SourceFile:161)
241662 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at d.l.a.b.j.b(SourceFile:15)
241663 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at d.l.a.b.j.a(SourceFile:142)
241664 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at d.l.a.b.j.a(SourceFile:34)
241665 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at d.l.a.b.j.a(SourceFile:14)
241666 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at com.skt.tmap.auto.activity.TmapAutoNaviActivity.c(SourceFile:129)
241667 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at com.skt.tmap.auto.activity.TmapAutoNaviActivity.a(SourceFile:9)
241668 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at com.skt.tmap.auto.activity.TmapAutoNaviActivity$v0.e(SourceFile:24)
241669 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at d.i.d.o.b.f.d3.a(SourceFile:7)
241670 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at d.i.d.o.b.f.d3.a(SourceFile:247)
241671 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at d.i.d.l.k.q5$h.a(SourceFile:33)
241672 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at d.i.d.l.k.q5$d.onFinish(SourceFile:4)
241673 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
241674 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at android.os.Handler.dispatchMessage(Handler.java:106)
241675 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at android.os.Looper.loop(Looper.java:247)
241676 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at android.app.ActivityThread.main(ActivityThread.java:8656)
241677 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at java.lang.reflect.Method.invoke(Native Method)
241678 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
241679 | 12-22 | 18:14:14.221 | E | 26889 | 26889 | AndroidRuntime: |   | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)


</body>
</html>
```
[LogFilter_20211222_181435.txt.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7761484/LogFilter_20211222_181435.txt.zip)

**Comment by aqkhsg** [comment]
이 이슈에 대한 추가설명은 없을까요?

**Comment by jhanulis7** [comment]
네.. 특별히 스팟성이라.. 크래쉬 로그로 확인해야 될거 같습니다.
테스트 버젼은 0.11.1 입니다.

**Comment by aqkhsg** [comment]
크래쉬 로그 확인하여 수정하였고 12.24일 배포에 적용

**Comment by jhanulis7** [comment]
크래쉬 재현 확인 어려우므로, 수정확인으로 이슈 클로스 합니다.
